import type { Metadata } from "next";
// changing font
import { Anek_Bangla } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/home/navbar";
import Footer from "@/components/home/Footer";

const AnekBangla = Anek_Bangla({
  // lagbe na
  // variable: "--font-geist-sans",
  subsets: ["latin","bengali"],
});
// lagbe na
// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${AnekBangla.className}  h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
          <Navbar></Navbar>
        {children}
        <Footer></Footer>
      </body>
    </html>
  );
}
